# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mingc/android-build-box:latest

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - chmod +x gradlew
#         - ./gradlew assembleDebug
          - ./gradlew test
          - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
          - emulator -avd testAVD -no-audio -no-window &
          - ./scripts/android-wait-for-emulator.sh
          - adb devices
          - adb shell settings put global window_animation_scale 0 &
          - adb shell settings put global transition_animation_scale 0 &
          - adb shell settings put global animator_duration_scale 0 &
          - adb shell input keyevent 82 &
          - ./gradlew connectedAndroidTest
          - ./scripts/stop-emulators.sh
